### ISSUE TITLE
mkosi fails on Python 3.4

### ISSUE THREAD

**Issue by eliasp** [systemd/mkosi#79]
`mkosi` can't be executed on Python 3.4-based distributions (e.g. current Debian stable 8.7 which only ships 3.4.2) due to various Python 3.5 specific items:

- [Line 636](https://github.com/systemd/mkosi/blob/0910ed5dbc3b089703b4a888d58ab96c4bace5f7/mkosi#636):
    **Code:**
    ```
    cmdline += ['--', *cmd]
    ```
    **Error**: SyntaxError: can use starred expression only as assignment target
- [Line 724](https://github.com/systemd/mkosi/blob/0910ed5dbc3b089703b4a888d58ab96c4bace5f7/mkosi#L724)
    **Code:**
    ```
    "--disablerepo=*",
    *repos,
    "--setopt=keepcache=1",
    ```
    **Error**: SyntaxError: can use starred expression only as assignment target
- [Line 125](https://github.com/systemd/mkosi/blob/0910ed5dbc3b089703b4a888d58ab96c4bace5f7/mkosi#L125)
    **Code:**
    ```
    subprocess.run(["mount", "--make-rslave", "/"], check=True)
    ```
    **Error**: AttributeError: 'module' object has no attribute 'run'
    **Note**: The `run()` method in `subprocess` was introduced in Python 3.5

Either `setup.py` needs to be adjusted to check for Python >= 3.5 (leaving Distributions without Python 3.5 unsupported) or the offending items need to be changed to also work with Python < 3.5.

**Comment by keszybz** [comment]
The first two are rather trivial, and we could replace `run` with `check_call`. So it's probably worth the trouble to support Debian.

**Comment by eliasp** [comment]
…on the other hand: Debian 8.x still has only systemd-215 - is this sufficient at all for what `mkosi` does using `systemd-nspawn`?

**Comment by fsateler** [comment]
Moreover, debian stretch is coming out ["really soon now"](https://lists.debian.org/debian-devel-announce/2017/04/msg00013.html):

> At the time of writing, 143 RC bugs affected stretch. Just one of them is marked as a blocker and unfixed in sid

 I'd just make 3.5 required.

**Comment by lucaswerkmeister** [comment]
Well, we’ve also wanted to release mkosi v2 for a while now (#68), so perhaps we could at least make this release Python 3.4-compatible.

**Comment by keszybz** [comment]
Hm, I looked into this, and it's not as simple as I thought. We have a bazillion `run` calls, which are mostly easy to convert (`subprocess.check_call(...)` is actually shorter than `subprocess.run(..., check=True)`), but then some use `subprocess.run(..., input=...)` which would require using `check_call` with `stdin=subprocess.PIPE` and then `.communicate` or such. So I'm leaning towards requiring python3.5, unless somebody who actually uses old Debian steps up and submits a patch.

**Comment by poettering** [comment]
I am fine with simply requiring Python 3.5
